### ISSUE TITLE
description type: description": "[Embryonic founder cell]",

### ISSUE THREAD

**Issue by jusa3** [ts4nfdi/api-gateway#25]
https://ts4nfdi-api-gateway.prod.km.k8s.zbmed.de/api-gateway/search?query=d&ontology=mesh,efo&type=class&collection=nfdi4health&fieldList=description,label,iri,ontology_name,type,short_form

OLS4 uses Arrays:

https://www.ebi.ac.uk/ols4/api/select?q=diab&ontology=mesh,efo&type=class&collection=nfdi4health&fieldList=description,label,iri,ontology_name,type,short_form

**Comment by syphax-bouazzouni** [comment]
Fixed in #26, now description and synonym fields  are a list 
![image](https://github.com/user-attachments/assets/18debca5-5760-43e3-8bd5-28ac0230daf8)
