### ISSUE TITLE
keyword database is not working anymore as expected

### ISSUE THREAD

**Issue by rombaum** [ts4nfdi/api-gateway#30]
I did a query via the [TSS autocomplete widget](https://ts4nfdi.github.io/terminology-service-suite/comp/latest/?path=/story/react_autocompletewidget--use-api-gateway-with-skosmos) and I used the parameter **database** with the value **skosmos**. I entered **milk** into the search input field. I would expect as a response only one concept from Agrovoc but i got multiple back. I would guess that the reason for this could be the added local indexer. It was working as describe at the end of July. The similar behavior appears when I use **ols** or **ontoportal** as values of **database**.

![image](https://github.com/user-attachments/assets/b5bc141b-44cf-4d78-8b3d-468efeca286c)

**Comment by syphax-bouazzouni** [comment]
fixd in https://github.com/ts4nfdi/api-gateway/issues/30
![image](https://github.com/user-attachments/assets/9fb81a23-883d-4627-b665-97d8be3c9b0a)
